### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by huangboju** [castial/HYAlertController#1]
用下这个，规范下代码[SwiftLint](https://github.com/realm/SwiftLint)

自己写的库尽量不要引用别的库啊

**Comment by iafine** [comment]
有时间会往这方面去做的，谢谢建议！

**Comment by huangboju** [comment]
@castial 
我把Snapkit依赖去掉了，优化了你的代码。已提PR，有时间看看

**Comment by iafine** [comment]
@huangboju ，写的不错，最近有点忙，有空我会好好看下，谢谢PR🙏

**Comment by iafine** [comment]
@huangboju 
写的不错，有空我会好好看下的🙏🙏，感谢PR。

>谢谢建议！最近太忙，准备农历年底出一个稳定的版本，可能会有大的改动，包括设计结构、语法上可能会更Swift化，你的建议也在我的计划之内^_^
