### ISSUE TITLE
旋转屏幕的时候， 遮罩视图只遮住了一般。

### ISSUE THREAD

**Issue by laughingg** [castial/HYAlertController#3]
1. 
![snip20161215_23](https://cloud.githubusercontent.com/assets/11444704/21211080/72a6d442-c2bb-11e6-844c-16e401cbc7ea.png)

2. 使用了三个 tableview .   可以考虑一下是否方案太臃肿。 可以考虑 UIStackView 
3. 三个弹出视图可以抽取一个父类出来。 这样可以省去很多代码
4. HY_Constants 没有必要继承自 UIView . HY_Constants 没有用到 UIView 的任何东西。 单纯是一个工具类，不考虑继承可以使用结构体。
5. 内部布局用到了 SnapKit lib .  从你布局代码的书写来看。 你可以自己以系统 autolayout  为基础写几个加约束的工具方法。（不是特别依赖其他第三方库，不建议在自己的第三方库中使用第三方库）
   只有  HYAlertCell 和  HYShareCollectionCell 中的少量布局代码使用了 SnapKit

**Comment by iafine** [comment]
>谢谢建议！最近太忙，准备年底出一个稳定的版本，可能会有大的改动，包括设计结构、语法上可能会更Swift化，你的建议也在我的计划之内^_^
